format = """
$directory\
$git_branch\
$git_status\
$cmd_duration\
$character"""

[directory]
style = "bold blue"
read_only = " 🔒"
truncation_length = 3
truncate_to_repo = true

[character]
# Das Symbol ändert sich, je nachdem ob du im Fish Insert- oder Normal-Modus bist
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold yellow)"

[git_branch]
symbol = ""
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2_000
format = "took [$duration](bold yellow) "
